### ISSUE TITLE
Instantly closes

### ISSUE THREAD

**Issue by DiamC23** [KillzXGaming/Cafe-Shader-Studio#2]
When I try opening it, it instantly closes. I tried unblocking the zip before extracting as well. GPU is NVIDIA GeForce GTX 1050.

**Comment by KillzXGaming** [comment]
Can you try running it from the command line and see if any errors show up?

**Comment by KillzXGaming** [comment]
I assume the latest build should now work, but if it doesn't you can re open this issue.
